---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-eks-role terraform module
  name: iam-eks-role
spec:
  dependsOn:
  - resource:aws_iam_role-this
  - resource:aws_iam_role_policy_attachment-this
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - create_role
  - role_name
  - role_path
  - role_permissions_boundary_arn
  - role_description
  - role_name_prefix
  - role_policy_arns
  - cluster_service_accounts
  - tags
  - force_detach_policies
  - max_session_duration
  - allow_self_assume_role
  - assume_role_condition_test
  subcomponentOf: resourcecomponent:iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role with name this
  name: aws_iam_role-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role_policy_attachment with name this
  name: aws_iam_role_policy_attachment-this
spec:
  owner: platform_team
  type: terraform
