---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-role-for-service-accounts-eks terraform module
  name: iam-role-for-service-accounts-eks
spec:
  dependsOn:
  - resource:aws_iam_role-this
  - resource:aws_iam_role_policy_attachment-this
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - create_role
  - role_name
  - role_path
  - role_permissions_boundary_arn
  - role_description
  - role_name_prefix
  - policy_name_prefix
  - role_policy_arns
  - oidc_providers
  - tags
  - force_detach_policies
  - max_session_duration
  - assume_role_condition_test
  - allow_self_assume_role
  - attach_aws_gateway_controller_policy
  - attach_cert_manager_policy
  - cert_manager_hosted_zone_arns
  - attach_cluster_autoscaler_policy
  - cluster_autoscaler_cluster_ids
  - cluster_autoscaler_cluster_names
  - attach_ebs_csi_policy
  - ebs_csi_kms_cmk_ids
  - attach_efs_csi_policy
  - attach_external_dns_policy
  - external_dns_hosted_zone_arns
  - attach_external_secrets_policy
  - external_secrets_ssm_parameter_arns
  - external_secrets_secrets_manager_arns
  - external_secrets_kms_key_arns
  - external_secrets_secrets_manager_create_permission
  - attach_fsx_lustre_csi_policy
  - fsx_lustre_csi_service_role_arns
  - attach_karpenter_controller_policy
  - karpenter_controller_cluster_id
  - karpenter_controller_cluster_name
  - karpenter_tag_key
  - karpenter_controller_ssm_parameter_arns
  - karpenter_controller_node_iam_role_arns
  - karpenter_subnet_account_id
  - karpenter_sqs_queue_arn
  - enable_karpenter_instance_profile_creation
  - attach_load_balancer_controller_policy
  - attach_load_balancer_controller_targetgroup_binding_only_policy
  - load_balancer_controller_targetgroup_arns
  - attach_appmesh_controller_policy
  - attach_appmesh_envoy_proxy_policy
  - attach_amazon_managed_service_prometheus_policy
  - amazon_managed_service_prometheus_workspace_arns
  - attach_velero_policy
  - velero_s3_bucket_arns
  - attach_vpc_cni_policy
  - vpc_cni_enable_ipv4
  - vpc_cni_enable_ipv6
  - attach_node_termination_handler_policy
  - node_termination_handler_sqs_queue_arns
  - attach_cloudwatch_observability_policy
  subcomponentOf: iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role with name this
  name: aws_iam_role-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role_policy_attachment with name this
  name: aws_iam_role_policy_attachment-this
spec:
  owner: platform_team
  type: terraform
