---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-account terraform module
  name: iam-account
spec:
  dependsOn:
  - resource:aws_iam_account_alias-this
  - resource:aws_iam_account_password_policy-this
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - get_caller_identity
  - account_alias
  - create_account_password_policy
  - max_password_age
  - minimum_password_length
  - allow_users_to_change_password
  - hard_expiry
  - password_reuse_prevention
  - require_lowercase_characters
  - require_uppercase_characters
  - require_numbers
  - require_symbols
  subcomponentOf: resourcecomponent:iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_account_alias with name this
  name: aws_iam_account_alias-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_account_password_policy with name this
  name: aws_iam_account_password_policy-this
spec:
  owner: platform_team
  type: terraform
