---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-assumable-roles terraform module
  name: iam-assumable-roles
spec:
  dependsOn:
  - resource:aws_iam_role-admin
  - resource:aws_iam_role_policy_attachment-admin
  - resource:aws_iam_role-poweruser
  - resource:aws_iam_role_policy_attachment-poweruser
  - resource:aws_iam_role-readonly
  - resource:aws_iam_role_policy_attachment-readonly
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - trusted_role_actions
  - trusted_role_arns
  - trusted_role_services
  - mfa_age
  - allow_self_assume_role
  - create_admin_role
  - admin_role_name
  - admin_role_path
  - admin_role_requires_mfa
  - admin_role_policy_arns
  - admin_role_permissions_boundary_arn
  - admin_role_tags
  - create_poweruser_role
  - poweruser_role_name
  - poweruser_role_path
  - poweruser_role_requires_mfa
  - poweruser_role_policy_arns
  - poweruser_role_permissions_boundary_arn
  - poweruser_role_tags
  - create_readonly_role
  - readonly_role_name
  - readonly_role_path
  - readonly_role_requires_mfa
  - readonly_role_policy_arns
  - readonly_role_permissions_boundary_arn
  - readonly_role_tags
  - max_session_duration
  - force_detach_policies
  subcomponentOf: resourcecomponent:iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role with name admin
  name: aws_iam_role-admin
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role_policy_attachment with name admin
  name: aws_iam_role_policy_attachment-admin
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role with name poweruser
  name: aws_iam_role-poweruser
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role_policy_attachment with name poweruser
  name: aws_iam_role_policy_attachment-poweruser
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role with name readonly
  name: aws_iam_role-readonly
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_role_policy_attachment with name readonly
  name: aws_iam_role_policy_attachment-readonly
spec:
  owner: platform_team
  type: terraform
