---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-group-with-assumable-roles-policy terraform module
  name: iam-group-with-assumable-roles-policy
spec:
  dependsOn:
  - resource:aws_iam_policy-this
  - resource:aws_iam_group-this
  - resource:aws_iam_group_policy_attachment-this
  - resource:aws_iam_group_membership-this
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - name
  - path
  - assumable_roles
  - group_users
  - tags
  subcomponentOf: iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_policy with name this
  name: aws_iam_policy-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_group with name this
  name: aws_iam_group-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_group_policy_attachment with name this
  name: aws_iam_group_policy_attachment-this
spec:
  owner: platform_team
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_group_membership with name this
  name: aws_iam_group_membership-this
spec:
  owner: platform_team
  type: terraform
