---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  description: iam-github-oidc-provider terraform module
  name: iam-github-oidc-provider
spec:
  dependsOn:
  - resource:aws_iam_openid_connect_provider-this
  environment:
  - test
  lifecycle: experimental
  owner: platform_team
  parent:
  - iam
  providesVariables:
  - create
  - tags
  - client_id_list
  - url
  - additional_thumbprints
  subcomponentOf: iam
  type: terraform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: resource aws_iam_openid_connect_provider with name this
  name: aws_iam_openid_connect_provider-this
spec:
  owner: platform_team
  type: terraform
